### ISSUE TITLE
fails to install from in-app plug-in directory (including sandbox vault)

### ISSUE THREAD

**Issue by shapesinaframe** [stephendolan/obsidian-calendar-event-sync#4]
Plugin fails to install from in-app plug-in directory  :frowning_face: 
Happens in both a user vault and the sandbox vault.

**Comment by stephendolan** [comment]
I can reproduce this, @shapesinaframe . Sorry about that!

I've got a v2 of this plugin that I'm at the 99% mark on that will bring a handy dandy "Select your event" modal to this plugin:
![CleanShot 2024-10-22 at 13 45 37](https://github.com/user-attachments/assets/5179961a-9c0d-4da3-bb04-4b46c612c784)


I'll aim to get it tagged and shipped this week, and see if that resolves the install issues.

**Comment by stephendolan** [comment]
@shapesinaframe I'm able to install the plugin from the directory successfully with the 2.0.0 release I just tagged.

Please re-open if this is still an issue!
