### ISSUE TITLE
Attendees don't show on ICS from Outlook Calendar

### ISSUE THREAD

**Issue by federomano** [stephendolan/obsidian-calendar-event-sync#5]
Events are listed correctly, but when selecting one, Attendees are not listed.

I have a Google account and Attendees show correctly, so this is happening specifically with my Outlook account ICS. 

<img width="735" alt="image" src="https://github.com/user-attachments/assets/6831a94a-5065-4629-80bd-0e376fd38a8f">

**Comment by stephendolan** [comment]
Thanks for the report, @federomano!

I don't have an Outlook account, but if you're down to make a small calendar that shows the issue and send me the ICS URL, I'll be glad to spend some time digging in to see what's going on 😊

**Comment by federomano** [comment]
Thanks @stephendolan!
Here's my test calendar, it has only 1 event, with 3 attendees in the invite:
https://outlook.office365.com/owa/calendar/d52ea36eeb45497fb6fcb5bba7ac60b7@itx.com/f481c9c91519405daad3925ee89c811211704295019915104267/calendar.ics

In the sharing permissions of Outlook, i've put "Can view all details" which is supposed to share not only event names but also attendees.

**Comment by stephendolan** [comment]
@federomano I got a couple of releases out this morning to hopefully handle this more gracefully. That said, I figured out the core of the issue!

Your ICS URL doesn't actually return any attendee data! You can see this by downloading the ICS file above and opening it in a text editor. It looks like Outlook might obscure these details intentionally; there could be a setting or something you need to tweak!

I'm closing this for now, but I'm happy to re-open if you can verify that the ICS URL has attendees and that they aren't showing up.

**Comment by federomano** [comment]
You are right, the ICS is of a work email and unfortunately i can't modify that setting, im really sorry i opened this issue! 🤦‍♀️ hope it doesn't open again with this comment 😅 thanks a lot for the context!
